fix: include board/config.h in all driver source files
The driver .c files need to include board/config.h first to get
stm32h7xx.h (which defines ADC_TypeDef) before including drivers.h.

This fixes the build error:
  lladc_declarations.h:29:3: error: unknown type name 'ADC_TypeDef'